name: App CD

on:
  pull_request:
    branches: ["main"]

  push:
    branches: ["main"]

env:
  SSH_AUTH_SOCK: /tmp/ssh_agent.sock

jobs:
  main:
    runs-on: macos-latest
    steps:    

      - name: Setup java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: "17.x"

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: '3.29.3'

      - name: Get Flutter packages
        run: |
          flutter pub get

      - name: Build APK
        run: flutter build apk --release
        
      - name: Install Firebase CLI
        run: |
          curl -sL https://firebase.tools | bash

      - name: Upload to Firebase App Distribution
        run: |
          firebase appdistribution:distribute build/app/outputs/flutter-apk/app-release.apk \
            --app "1:105900131676:android:9884b736c70de108382d99" \
            --groups "testers" \
            --release-notes "Nova build automática via GitHub Actions" \
            --token "1//0hS5F72SmOgVGCgYIARAAGBESNwF-L9IrhN84epW9hLFeBUN676JglDTaL8ryQ6MNGMm37dyjPHVjFjuC9uN594cl8A6UtIi16z4"

      # - name: Build appBundle
      #   run: flutter build appbundle

      # - name: Build iOS App
      #   run: |
      #     flutter build ios --profile --no-codesign
      #     cd build/ios/iphoneos
      #     mkdir Payload
      #     cd Payload
      #     ln -s ../Runner.app
      #     cd ..
      #     zip -r app.ipa Payload      


      # - name: Upload Artifacts
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: Releases
      #     path: |
      #       build/app/outputs/flutter-apk/app-release.apk
      #       build/app/outputs/bundle/release/app-release.aab
      #       build/ios/iphoneos/app.ipa



